apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zxkyc9y8w-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zxkyc9y8w-python 
  name: zxkyc9y8w-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zxkyc9y8w-python 
